name = "tollgate-release-explorer"
compatibility_date = "2024-03-18"

[env.production]
name = "tollgate-release-explorer"

[env.preview]
name = "tollgate-release-explorer-preview"

# Build configuration for React app
[build]
command = "npm run build"
cwd = "."
watch_dir = "src"

# Pages configuration
[[pages_build_output_dir]]
directory = "build"

# Environment variables (if needed)
[vars]
NODE_ENV = "production"

# Custom domains
[env.production.routes]
pattern = "releases.tollgate.me"
zone_name = "tollgate.me"

# Security headers
[[headers]]
for = "/*"
[headers.values]
X-Frame-Options = "DENY"
X-Content-Type-Options = "nosniff"
Referrer-Policy = "strict-origin-when-cross-origin"
Permissions-Policy = "camera=(), microphone=(), geolocation=()"

# Cache control for static assets
[[headers]]
for = "/static/*"
[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
for = "*.js"
[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
for = "*.css"
[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
for = "*.png"
[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
for = "*.jpg"
[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
for = "*.svg"
[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

# SPA fallback - serve index.html for all routes
[[redirects]]
from = "/*"
to = "/index.html"
status = 200
conditions = ["Not Static"]